# Generated by Django 4.2.30 on 2026-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
