# Generated by Django 4.2.30 on 2026-06-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_issue_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="estimate_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
